### ISSUE TITLE
[Question] Blink ID Self-hosted API

### ISSUE THREAD

**Issue by troymcginnis** [Blue-Sky-Operations-GmbH/MAX-Backend-Issues#69]
@cohrsd @BSO-Lukas It looks like we've been using the in-browser BlinkID service that runs off of the hosted MicroBlink service rather than the self-hosted version of the Web API.

Is there a BlueSky instance/URL of the MicroBlink API that we can access for this?

**Comment by BSO-Lukas** [comment]
@troymcginnis https://microblink.bso-projects.com/
Just let me know if you access the api

**Comment by ProgrammingJoe** [comment]
Hi @BSO-Lukas I assume these are the docs I should be referring to? https://docs.microblink.com/documentation/self-hosted/current/overview.html#introduction

I'm currently getting a 400 error with this request 

<img width="720" height="422" alt="Image" src="https://github.com/user-attachments/assets/7f9c211f-b748-4548-97f2-7215942b99f5" />

Is auth setup on this endpoint? Do we need a username and password?

**Comment by troymcginnis** [comment]
@ProgrammingJoe This should be resolved now. Mind trying again?

**Comment by ProgrammingJoe** [comment]
@troymcginnis I've tried a few different formats but still no luck. A couple below. This endpoint isn't defined in the API docs so I'm not sure what format to use

<img width="1618" height="836" alt="Image" src="https://github.com/user-attachments/assets/9418fef5-a6e5-4a8a-bb9c-ea84ad5b54cf" />

<img width="1638" height="942" alt="Image" src="https://github.com/user-attachments/assets/f7cf8562-26fc-47b1-b394-0dc2f5859b79" />

**Comment by ProgrammingJoe** [comment]
It also doesn't seem to follow the doc format: https://docs.microblink.com/documentation/self-hosted/current/overview.html#quick-setup-guide

**Comment by troymcginnis** [comment]
@ProgrammingJoe Have you taken a look at the endpoint docs: https://docs.microblink.com/documentation/self-hosted/current/overview.html?javascript#blinkidmultiside or the OpenAPI spec: https://docs.microblink.com/documentation/self-hosted/current/overview.html?javascript#openapi-3?

**Comment by BSO-Lukas** [comment]
@troymcginnis 
can we close this issue for now?
